version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=Pass@word
    ports:
      - "1435:1433"

  customer-api:
    image: ovibhuiyan43/customer-api:v1
    build:
      context: .
      dockerfile: Customer.API/Dockerfile
    depends_on:
      - sqlserver
    restart: on-failure
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__CustomerDBConnection=Server=sqlserver;Database=CustomerDB;user id=sa;password=Pass@word;
  
  customer-web:
    image: ovibhuiyan43/customer-web:v1
    build:
      context: .
      dockerfile: Customer.WEB/Dockerfile
    depends_on:
      - customer-api
    ports:
      - "6110:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CustomerService__ApiURL=http://customer-api
        

volumes:
  sqlserverdata:
    #external: true   

    #external resource



