version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      #- MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2
    restart: always
    ports:
      - "1435:1433"

  customer.api:
    image: customerapi:latest
    build:
      context: .
      dockerfile: Customer.API/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5100:80"
    environment:
      - ConnectionStrings__CustomerDBConnection=Server=sqlserver;Database=CustomerDB;user id=sa;password=8jkGh47hnDw89Haq8LN2
      #- ConnectionString=${Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word}
  customer.web:
    image: customerweb:latest
    build:
      context: .
      dockerfile: Customer.WEB/Dockerfile
    depends_on:
      - customer.api
    ports:
      - "6100:80"
    environment:
      - CustomerService__ApiURL=http://customer.api


volumes:
  sqlserverdata:
#    #external: true   