apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api-deployment
spec:
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - name: customer-api
        image: microservice/customer-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
