apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-web-deployment
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: customer-web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: customer-web
    spec:
      containers:
      - name: customer-web
        image: ovibhuiyan43/customer-web:v1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: CustomerService__ApiURL
            value: "http://customer-api-service"
            # value: "http://192.168.0.250:5100"
      restartPolicy: Always   
---
apiVersion: v1
kind: Service
metadata:
  name: customer-web-service
spec:
  type: LoadBalancer
  selector:
    app: customer-web
  ports:
  - name: http-6100
    port: 6100 # extarnal port
    targetPort: 80 #internal port

