apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: "Developer"
          - name: SA_PASSWORD
            value: "Pass@word"
          
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  type: LoadBalancer
  selector:
    app: sqlserver
  ports:
  - name: http-1435
    port: 1435 # extarnal port
    targetPort: 1433 #internal port


# ---  have to create volume