apiVersion: v1
kind: Service
metadata:
  name: {{ template "customerapi.fullname" . }}
  labels:
    app: {{ template "customerapi.name" . }}
    chart: {{ template "customerapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      
      #namem: http
      #new: service
      #grow: grownservice.http.tcp.8080.port.application.
      #names: application
      #as-job: home.name.game.sundar.jibon.name.dimon.jibon.shomossha
      #pi-job: service.host.new.pi-job.ajkei shob up dia dei. video shoho. taile boost korlw kew duklew dekhte parbo video


  selector:
    app: {{ template "customerapi.name" . }}
    release: {{ .Release.Name }}
