name: cutomer-api

on:
  push:
    branches: 
    - master
    
    paths:
    - Customer.API/**
    - .github/workflows/customer-api.yml
  
  pull_request:
    branches:
    - master
    
    paths:
    - Customer.API/**
    - .github/workflows/customer-api.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   # - name: Restore dependencies
  #    run: dotnet restore Microservice.sln
    - name: Build
      run: dotnet build
      working-directory: ./Customer.API
  
    - name: Unit Test
      run: dotnet test
      working-directory: ./Customer.API.Test
    - name: Intigration Test
      run: dotnet test
      working-directory: ./CustomerAPI.Intigration.Test
