name: cutomer-api

on:
  push:
    branches: 
    - master
    
    paths:
    - Customer.API/**
    - .github/workflows/customer-api.yml
  
  pull_request:
    branches:
    - master
    
    paths:
    - Customer.API/**
    - .github/workflows/customer-api.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Microservice.sln
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Customer.API
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Customer.API.Test
